[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  REACT_APP_SERVER_URL = "https://0264a4ca-18ae-4b7b-a405-913b6055804e.mock.pstmn.io"